name: Bug report 🐛
description: File a bug report
title: "[Bug] <insert descriptive title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve Taiko!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug and expected behavior.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug.
  - type: textarea
    id: additional-details
    attributes:
      label: Additional details
      description: Please add any additional details, screenshots, logs, etc.
