name: Bug report 🐛
description: File a bug report
title: "[Bug] <insert descriptive title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve Taiko! Before submitting, please check if an existing issue already exists.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: Description of the bug here.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug.
      value: Steps to reproduce here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please add any additional context, screenshots, etc.
      value: Additional context here.
