name: Add a project to Taiko's ecosystem 🌐
description: "Add a project to Taiko's ecosystem. You can see Taiko's ecosystem page here: https://taiko.xyz/ecosystem."
labels: ["category.enhancement", "status.needs-triage"]
body:
  - type: input
    id: title
    attributes:
      label: Title of your project
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to your project
    validations:
      required: true
  - type: textarea
    id: logo
    attributes:
      label: High quality logo to your project
      description: 512x512 or 1:1 ratio is preferred. If you don't have one that's okay, and we will use a placeholder image.
    validations:
      required: false
