name: Add a project to Taiko's ecosystem 🌐
description: "Add a project to Taiko's ecosystem. You can see Taiko's ecosystem page here: https://taiko.xyz/ecosystem."
labels: ["category.enhancement", "status.needs-triage"]
assignees:
  - d1onys1us
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add to Taiko's ecosystem! You can see existing examples [here](https://taiko.xyz)
  - type: input
    id: title
    attributes:
      label: Title of your project
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to your project
    validations:
      required: true
  - type: textarea
    id: logo
    attributes:
      label: Upload a quality logo to your project
      description: 512x512 or 1:1 ratio is preferred. If you don't have one that's okay, and we will use a placeholder image.
    validations:
      required: false
